### PR TITLE
Script and fixes to install a full FreeDOS 1.2.

### PR DESCRIPTION
**Pull request by jschwartzenberg**
Renamed the one script.  Now install scripts will always do both download+setup.

### CODE REVIEW

**Comment by stsp** [comment]
What does it mean full?
IIRC we have another repo,
install-otherdos, that can also
install freedos.

Also please make the commit
description proper. You need
a short descr on the first line,
then empty line, then full descr.

Otherwise it looks quite badly,
see yourself:
https://github.com/dosemu2/install-freedos/pull/3/commits/eead759cf844d8f5b6e89e4732cd2786f7169af3

**Comment by jschwartzenberg** [comment]
Good point, I cleaned up the description now and extended it a bit. Full means also the kernel and command.com come from FreeDOS (and it's therefore put below `install/freedos12`.
This is a very basic script which doesn't show a menu, but can use the logic already available in this repository to install a full FreeDOS 1.2 without interaction. The other repository add the menu to pick a specific DOS version from and the ability to install non-FreeDOS as well.

**Comment by stsp** [comment]
This is quite a bad split.
Lets have only user-space part here,
and the rest in another repo.

**Comment by jschwartzenberg** [comment]
Yeah, that's true. I will have to think how to rework this though. I will create some smaller PRs on this.

**Pull request closed without merging**
