### PR TITLE
Add xcopy

### PR DESCRIPTION
**Pull request by andrewbird**

### CODE REVIEW

**Comment by stsp** [comment]
Please add a description.
There apparently was `xcopy` already,
so what have happened?

**Comment by stsp** [comment]
And `share` too...
And no description???

**Comment by andrewbird** [comment]
Force pushed.

**Comment by stsp** [comment]
Hmm, since when it became unused?
But anyway, there is a comment that
says its unused, so let's apply.
Thanks.

**Comment by andrewbird** [comment]
The comment is mine, I noticed it was unused when I added the --test option. I'm not sure when it became unused, or if it was ever used.

**Pull request merged**
